server:
   port: 9001
   
spring:  application:    name: DEPARTMENT-SERVICE

   
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
        defaulZone: http://localhost:8761/euraka/
  instance:
    hostname: localhost 